### ISSUE TITLE
Feed not updating

### ISSUE THREAD

**Issue by rapha8l** [derat/twittuh#12]
When using :
`twittuh -force -format json -verbose archillect archillect.json`

I get : 

`2021/10/13 20:30:02 Failed getting archillect: failed fetching timeline: failed loading tweets: context canceled`

Thanks

**Comment by derat** [comment]
You might want to try increasing some of the timeouts to see if it helps (`-fetch-timeout` and `-tweet-timeout`, if memory serves). I can't offer much advice beyond that since I haven't used this code since April and it's basically unmaintained at this point -- see the comment near the top of `README.md`.

I recommend instead using [Nitter](https://github.com/zedeus/nitter), since (as I understand it) it just calls the Twitter backend directly and can produce RSS feeds. I wrote [a small proxy](https://github.com/derat/nitter-rss-proxy) that can round-robin between public Nitter instances to serve RSS feeds.

**Comment by rapha8l** [comment]
Thanks !
I'll try

**Comment by derat** [comment]
Good luck! If you try changing the timeouts, you can see the flags that I was passing the last time I used this code in the [Dockerfile](https://github.com/derat/twittuh/blob/master/Dockerfile). That was for a really cheap preemptible Google Compute Engine instance (but I had a lot of trouble with Twitter blocking GCE instances, and using Tor often made things too slow).

Nitter still seems like a safer bet since people are actively working on it, though. :-)

**Comment by rapha8l** [comment]
I'm using your proxy now, and it works great !
Thanks a lot again :)
